server:
  port: ${SERVER_PORT}

eureka:
  instance:
    instance-id: ${spring.application.name}(${EUREKA_INSTANCE_HOSTNAME}):${server.port}
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  server:
    registry-sync-retries: 3
    enable-self-preservation: false
  dashboard:
    path: /dashboard
  environment: dev

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health,info.metrics,loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    build:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix.eureka: DEBUG
    com.pharmaflow: DEBUG